image: alpine:3.4

# git lfs stuff from this thread
# https://gitlab.com/gitlab-org/gitlab-ce/issues/3489
# https://gitlab.com/gitlab-examples/lfs/blob/master/.gitlab-ci.yml
before_script:
  - apk update && apk add openssl
  - apk add git git-lfs --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/
  - git lfs pull
  - wget https://github.com/spf13/hugo/releases/download/v0.16/hugo_0.16_linux-64bit.tgz
  - echo "37ee91ab3469afbf7602a091d466dfa5  hugo_0.16_linux-64bit.tgz" | md5sum -c
  - tar xf hugo_0.16_linux-64bit.tgz && cp ./hugo /usr/bin
  - hugo version

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
