image: alpine:3.4

# git lfs stuff from this thread
# https://gitlab.com/gitlab-org/gitlab-ce/issues/3489
# https://gitlab.com/gitlab-examples/lfs/blob/master/.gitlab-ci.yml
# DOES NOT work - apk add git git-lfs --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/
# - wget https://github.com/spf13/hugo/releases/download/v0.19/hugo_0.19_linux-64bit.tgz
before_script:
  - apk update && apk add openssl git
  - apk add --update --virtual build-dependencies curl
  - curl -sLO https://github.com/github/git-lfs/releases/download/v2.0.1/git-lfs-linux-amd64-2.0.1.tar.gz
  - tar xf git-lfs-linux-amd64-2.0.1.tar.gz && mv git-lfs-2.0.1/git-lfs /usr/bin/ && rm -Rf git-lfs-2.0.1
  - git lfs pull
  - wget https://github.com/spf13/hugo/releases/download/v0.19/hugo_0.19_Linux-64bit.tar.gz
  - echo "3fc43b23a35dfe5290196bd0fc01f13f  hugo_0.19_Linux-64bit.tar.gz" | md5sum -c
  - tar xf hugo_0.19_Linux-64bit.tar.gz && cp ./hugo_0.19_linux_amd64/hugo_0.19_linux_amd64 /usr/bin
  - hugo_0.19_linux_amd64 version

pages:
  script:
  - hugo_0.19_linux_amd64
  artifacts:
    paths:
    - public
  only:
  - master
