baseurl: "/"
title: "Rufus Pollock Online"
languageCode: "en-us"
googleAnalytics: "UA-35035650-1"

# in hugo >= 0.60 suddenly switched off html! https://gohugo.io/news/0.60.0-relnotes/
markup:
  goldmark:
    renderer:
      unsafe: true

permalinks:
  post: /:year/:month/:day/:slug/

# themes: Information Economy, data systems, Wise Society, misc [notebook]
# tags: anything i want!
# projects: for list see projects database
# posttype: updates, talks, own-work, essays, notebook
# featured: yes, no
taxonomies:
  theme: "themes"
  tag: "tags"
  project: "projects"
  posttype: "posttypes"

params:
  github: https://github.com/rufuspollock/
  twitter: https://twitter.com/@rufuspollock/
  linkedin: https://www.linkedin.com/in/rufus-pollock-00a86348/
  youtube: https://www.youtube.com/@bylifeitself

